-- =====================================================================
-- Niks Masala — Supabase product seed (40 rows)
--
-- Why this exists
--   /functions/api/order/create.js looks up canonical prices in the
--   `products` table when an order is placed. If the table is empty, every
--   checkout fails with "Unknown product pX". This file backfills the same
--   catalog that assets/app.js ships to the browser as DEFAULT_PRODUCTS.
--
-- How to run
--   1. Open Supabase → SQL Editor → New query.
--   2. Paste this entire file.
--   3. Run. Safe to re-run — idempotent via ON CONFLICT (id) DO UPDATE.
--
-- After it runs
--   - Place a test order. The "Unknown product" toast disappears.
--   - To change a price / add a variant, edit assets/app.js, then re-run
--     this file (or update the row directly in Supabase).
-- =====================================================================

INSERT INTO products (id, name, slug, category, price, old_price, weight, image, variants, description, long_desc, badge, stock) VALUES
('p1','Turmeric Powder','turmeric-powder','Direct Grinding',25,NULL,'','assets/products/turmeric.webp','[{"pack":"50gm Pouch","grams":50,"price":25},{"pack":"100gm Pouch","grams":100,"price":45},{"pack":"200gm Pouch","grams":200,"price":85},{"pack":"500gm Pouch","grams":500,"price":250},{"pack":"50gm Box","grams":50,"price":30},{"pack":"100gm Box","grams":100,"price":55}]'::jsonb,'Stone-ground farm-fresh turmeric with high curcumin content. Pure and vibrant.','Stone-ground farm-fresh turmeric with high curcumin content. Pure and vibrant. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p2','Red Chilli Powder','red-chilli-powder','Direct Grinding',35,NULL,'','assets/products/red-chilli.webp','[{"pack":"50gm Pouch","grams":50,"price":35},{"pack":"100gm Pouch","grams":100,"price":60},{"pack":"200gm Pouch","grams":200,"price":120},{"pack":"500gm Pouch","grams":500,"price":300},{"pack":"100gm Box","grams":100,"price":60}]'::jsonb,'Bold, bright red chilli powder — sun-dried and traditionally ground.','Bold, bright red chilli powder — sun-dried and traditionally ground. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p3','Coriander Powder','coriander-powder','Direct Grinding',22,NULL,'','assets/products/coriander.webp','[{"pack":"50gm Pouch","grams":50,"price":22},{"pack":"100gm Pouch","grams":100,"price":45},{"pack":"200gm Pouch","grams":200,"price":85},{"pack":"500gm Pouch","grams":500,"price":250},{"pack":"100gm Box","grams":100,"price":50}]'::jsonb,'Freshly ground coriander — earthy, fragrant and kitchen-essential.','Freshly ground coriander — earthy, fragrant and kitchen-essential. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p4','Kashmiri Chilli Powder','kashmiri-chilli-powder','Direct Grinding',80,NULL,'','assets/products/kashmiri.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Vibrant red colour with mild heat. Sourced from premium Kashmiri chillies.','Vibrant red colour with mild heat. Sourced from premium Kashmiri chillies. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p5','Jeera Powder','jeera-powder','Direct Grinding',55,NULL,'','assets/products/jeera.webp','[{"pack":"50gm Pouch","grams":50,"price":55},{"pack":"50gm Box","grams":50,"price":60},{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":400}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p6','Black Pepper Powder','black-pepper-powder','Direct Grinding',80,NULL,'','assets/products/pepper.webp','[{"pack":"50gm Box","grams":50,"price":80},{"pack":"100gm Box","grams":100,"price":160},{"pack":"500gm Pouch","grams":500,"price":600}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p7','Garam Masala','garam-masala','Veg Specialities',40,NULL,'','assets/products/garam-masala.webp','[{"pack":"50gm Box","grams":50,"price":40},{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'The soul of Indian kitchens — a warm, balanced blend of hand-roasted whole spices.','The soul of Indian kitchens — a warm, balanced blend of hand-roasted whole spices. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p8','Super Garam Masala','super-garam-masala','Veg Specialities',35,NULL,'','assets/products/garam-masala.webp','[{"pack":"50gm Pouch","grams":50,"price":35},{"pack":"100gm Pouch","grams":100,"price":60},{"pack":"200gm Pouch","grams":200,"price":110},{"pack":"500gm Pouch","grams":500,"price":240}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p9','Udupi Sambar Masala','udupi-sambar-masala','Veg Specialities',80,NULL,'','assets/products/sambar.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Classic Udupi-style sambar masala with hand-roasted lentils, coriander and fenugreek.','Classic Udupi-style sambar masala with hand-roasted lentils, coriander and fenugreek. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p10','Super Sambar Masala','super-sambar-masala','Veg Specialities',350,NULL,'','assets/products/sambar.webp','[{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p11','Udupi Rasam Masala','udupi-rasam-masala','Veg Specialities',80,NULL,'','assets/products/rasam.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'A bowl of warmth rooted in tradition — light, aromatic and deeply comforting rasam blend.','A bowl of warmth rooted in tradition — light, aromatic and deeply comforting rasam blend. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p12','Vegetable Pulav Masala','vegetable-pulav-masala','Veg Specialities',80,NULL,'','assets/products/pulav.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p13','Chaat Masala','chaat-masala','Veg Specialities',80,NULL,'','assets/products/jaljeera.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":300}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p14','Chhole Masala','chhole-masala','Veg Specialities',80,NULL,'','assets/products/chhole.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p15','Jajeera Powder','jajeera-powder','Veg Specialities',80,NULL,'','assets/products/jeera.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p16','Pav Bhaji Masala','pav-bhaji-masala','Veg Specialities',80,NULL,'','assets/products/pav-bhaji.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p17','Sabji Masala','sabji-masala','Veg Specialities',40,NULL,'','assets/products/sabji-masala.webp','[{"pack":"50gm Box","grams":50,"price":40},{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p18','Puliyogare Powder','puliyogare-powder','Veg Specialities',80,NULL,'','assets/products/puliyogare.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p19','Chicken Ghee Roast Masala','chicken-ghee-roast-masala','Non-Veg Specialities',80,NULL,'','assets/products/ghee-roast.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":450}]'::jsonb,'A Mangalorean masterpiece — roasted spices, red chillies & pure ghee aroma. Bold, buttery and bursting with coastal flavour.','A Mangalorean masterpiece — roasted spices, red chillies & pure ghee aroma. Bold, buttery and bursting with coastal flavour. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.','BESTSELLER',50),
('p20','Chicken Kundapura Masala','chicken-kundapura-masala','Non-Veg Specialities',70,NULL,'','assets/products/kundapura.webp','[{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"100gm Box","grams":100,"price":80},{"pack":"200gm Jar","grams":200,"price":160},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Fiery and flavourful — the authentic taste of Mangalore''s famous kitchens, crafted with handpicked coastal spices.','Fiery and flavourful — the authentic taste of Mangalore''s famous kitchens, crafted with handpicked coastal spices. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p21','Chicken Sukka Masala (Mangalore No.1)','chicken-sukka-masala-mangalore-no-1','Non-Veg Specialities',70,NULL,'','assets/products/chicken-masala.webp','[{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'The iconic dry Mangalorean chicken preparation. Robust, fragrant and deeply traditional.','The iconic dry Mangalorean chicken preparation. Robust, fragrant and deeply traditional. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.','BESTSELLER',50),
('p22','Chicken Masala','chicken-masala','Non-Veg Specialities',40,NULL,'','assets/products/chicken-masala.webp','[{"pack":"50gm Box","grams":50,"price":40},{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Slow-cooked perfection in a packet — aromatic spices that blend into a rich, thick, flavourful gravy.','Slow-cooked perfection in a packet — aromatic spices that blend into a rich, thick, flavourful gravy. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p23','Super Chicken Masala','super-chicken-masala','Non-Veg Specialities',135,NULL,'','assets/products/chicken-masala.webp','[{"pack":"200gm Pouch","grams":200,"price":135}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p24','Chicken Pulimunchi Masala','chicken-pulimunchi-masala','Non-Veg Specialities',350,NULL,'','assets/products/chicken-masala.webp','[{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p25','Chicken Kabab / Chicken 65 Masala','chicken-kabab-chicken-65-masala','Non-Veg Specialities',40,NULL,'','assets/products/tandoori.webp','[{"pack":"100gm Pouch","grams":100,"price":40},{"pack":"200gm Pouch","grams":200,"price":75},{"pack":"500gm Pouch","grams":500,"price":250}]'::jsonb,'Juicy, crispy and bursting with bold spices — restaurant-style kabab & chicken 65 made easy.','Juicy, crispy and bursting with bold spices — restaurant-style kabab & chicken 65 made easy. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p26','Chicken Biriyani Masala','chicken-biriyani-masala','Non-Veg Specialities',400,NULL,'','assets/products/chicken-masala.webp','[{"pack":"500gm Pouch","grams":500,"price":400}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p27','Chicken Tandoori Masala','chicken-tandoori-masala','Non-Veg Specialities',80,NULL,'','assets/products/tandoori.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p28','Chicken Tikka Masala','chicken-tikka-masala','Non-Veg Specialities',80,NULL,'','assets/products/tikka.webp','[{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p29','Fish Curry Masala','fish-curry-masala','Non-Veg Specialities',60,NULL,'','assets/products/fish-masala.webp','[{"pack":"100gm Pouch","grams":100,"price":60},{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p30','Fish Pulimunchi Masala','fish-pulimunchi-masala','Non-Veg Specialities',60,NULL,'','assets/products/chicken-masala.webp','[{"pack":"100gm Pouch","grams":100,"price":60},{"pack":"500gm Pouch","grams":500,"price":350}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p31','Fish Fry Masala','fish-fry-masala','Non-Veg Specialities',40,NULL,'','assets/products/fish-masala.webp','[{"pack":"100gm Pouch","grams":100,"price":40},{"pack":"500gm Pouch","grams":500,"price":250}]'::jsonb,'Coastal fish-fry blend — authentic colour, aroma and that unforgettable crispy-outside, juicy-inside finish.','Coastal fish-fry blend — authentic colour, aroma and that unforgettable crispy-outside, juicy-inside finish. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.','BESTSELLER',50),
('p32','Mutton / Meat Masala','mutton-meat-masala','Non-Veg Specialities',40,NULL,'','assets/products/mutton.webp','[{"pack":"50gm Box","grams":50,"price":40},{"pack":"100gm Box","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":400}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p33','Bafath Masala','bafath-masala','Non-Veg Specialities',70,NULL,'','assets/products/mutton.webp','[{"pack":"100gm Pouch","grams":100,"price":70},{"pack":"500gm Pouch","grams":500,"price":400}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p34','Egg Curry Masala','egg-curry-masala','Non-Veg Specialities',250,NULL,'','assets/products/mutton.webp','[{"pack":"500gm Pouch","grams":500,"price":250}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p35','Kitchen King Masala','kitchen-king-masala','Veg Specialities',80,NULL,'','assets/products/kitchen-king.webp','[{"pack":"100gm Pouch","grams":100,"price":80},{"pack":"500gm Pouch","grams":500,"price":370}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p36','Compounded Asafoetida Powder','compounded-asafoetida-powder','Other Products',55,NULL,'','assets/products/garam-masala.webp','[{"pack":"25gm Jar","grams":25,"price":55},{"pack":"50gm Jar","grams":50,"price":100}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p37','Ginger-Garlic Paste','ginger-garlic-paste','Other Products',60,NULL,'','assets/products/garam-masala.webp','[{"pack":"200gm Jar","grams":200,"price":60}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p38','Niks Papad','niks-papad','Other Products',25,NULL,'','assets/products/garam-masala.webp','[{"pack":"80gm Pouch","grams":80,"price":25}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p39','Kasuri Methi','kasuri-methi','Other Products',38,NULL,'','assets/products/kasuri-methi.webp','[{"pack":"25gm Box","grams":25,"price":38}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50),
('p40','Soya Chunks','soya-chunks','Other Products',60,NULL,'','assets/products/soya.webp','[{"pack":"200gm Box","grams":200,"price":60},{"pack":"1 KG Pouch","grams":1000,"price":300}]'::jsonb,'Authentic Mangalorean spice blend — traditionally crafted, export-quality.','Authentic Mangalorean spice blend — traditionally crafted, export-quality. Packed at our FSSAI-certified, 11,000 sq.ft. facility in Yeyyadi, Mangalore.',NULL,50)
ON CONFLICT (id) DO UPDATE SET
  name        = EXCLUDED.name,
  slug        = EXCLUDED.slug,
  category    = EXCLUDED.category,
  price       = EXCLUDED.price,
  weight      = EXCLUDED.weight,
  image       = EXCLUDED.image,
  variants    = EXCLUDED.variants,
  description = EXCLUDED.description,
  long_desc   = EXCLUDED.long_desc,
  badge       = EXCLUDED.badge,
  stock       = EXCLUDED.stock;

-- Sanity check after running:
--   SELECT count(*) FROM products;        -- expect 40
--   SELECT id, name, price FROM products ORDER BY id LIMIT 5;
